version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.2.1

jobs:
  deploy:
    parameters:
      environment:
        type: string
    docker:
      - image: cimg/node:21.7
    environment:
      NODE_ENV: << parameters.environment >>
    steps:
      - checkout
      - run:
          name: Install Serverless Framework
          command: sudo npm install -g serverless@3.34.0
      - restore_cache:
          keys:
            - cache-v5-<< parameters.environment >>-{{ checksum "yarn.lock" }}
            - cache-v5-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Prune Dependencies
          command: |
            curl -sf https://gobinaries.com/tj/node-prune | sh
            sudo npm i -g modclean
            node-prune
            modclean --run
            git gc
      - save_cache:
          paths:
            - ./node_modules
          key: cache-v5-<< parameters.environment >>-{{ checksum "yarn.lock" }}
      - aws-cli/setup
      - run:
          name: Pull Environment Files
          command: yarn pull-envs
      - run:
          name: Serverless Deploy
          command: |
            NODE_ENV=<< parameters.environment >> npx serverless deploy \
              -c serverless.js \
              -s << parameters.environment >> \
              --verbose

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          name: deploy_staging
          context: build
          environment: staging
      - approve_production:
          type: approval
          requires:
            - deploy_staging
      - deploy:
          name: deploy_production
          context: build
          environment: production
          requires:
            - approve_production

